apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: dashboard-monolith
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
        - image: dev.local/dashboard-monolith:latest
          command: ["/bin/sh", "-c", "sleep 3600"]
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
