apiVersion: neon.molnett.org/v1alpha1
kind: NeonCluster
metadata:
  name: neon-cluster
  namespace: default
spec:
  # Configuration for the self-hosted Neon cluster
  # This assumes the operator is configured with S3 details
  pgVersion: 15
  compute:
    image: neondatabase/compute-node:latest
  pageserver:
    image: neondatabase/pageserver:latest
    storageClassName: standard
    size: 10Gi
  safekeeper:
    image: neondatabase/safekeeper:latest
    storageClassName: standard
    size: 10Gi
---
apiVersion: neon.molnett.org/v1alpha1
kind: NeonProject
metadata:
  name: my-project
  namespace: default
spec:
  clusterRef:
    name: neon-cluster
---
apiVersion: neon.molnett.org/v1alpha1
kind: NeonBranch
metadata:
  name: main
  namespace: default
spec:
  projectRef:
    name: my-project
  default: true
