apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: minio-tenant
  namespace: default
spec:
  image: minio/minio:RELEASE.2023-09-30T07-02-29Z
  imagePullPolicy: IfNotPresent
  pools:
    - servers: 2
      name: pool-0
      volumesPerServer: 2
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
  mountPath: /export
  requestAutoCert: false
  configuration:
    name: minio-creds
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-creds
  namespace: default
stringData:
  config.env: |-
    export MINIO_ROOT_USER="minio"
    export MINIO_ROOT_PASSWORD="minio123"
